from enum import Enum


class T(Enum):
    NOTAG = "NOTAG"

    FAM = "FAMILLE"
    SOIN = "SOIN"
    TECH = "TECH"
    # FIXE
    ABO = "ABO"
    FORFAIT = "FORFAIT"
    ASS = "ASSURANCE"
    HOUSE = "MAISON"
    CREDIT = "CREDIT"
    COPRO = "COPRO"
    ENER = "ENERGIE"
    MUSIC = "MUSIC"
    VOD = "VOD"
    CLOUD = "CLOUD"
    ENTRETIEN = "ENTRETIEN"

    COURSE = "COURSE"
    ALIM = "ALIMENTATION"
    SUPER = "SUPERMARCHE"
    SUPERETTE = "SUPERETTE"
    BOULANGE = "BOULANGERIE"
    SWILE = "SWILE"
    TRAITEUR = "TRAITEUR"
    BOULOT = "BOULOT"
    PRIMEUR = "PRIMEUR"
    KIDS = "KIDS"
    SCHOOL = "SCHOOL"
    FRINGUE = "VETEMENTS"
    SHOPPING = "SHOPPING"
    AMZ = "AMAZON"
    SPORT = "SPORT"
    CULTURE = "CULTURE"
    CHAT = "CHAT"
    LOISIRS = "LOISIRS"
    SORTIES = "SORTIES"
    PARC = "SORTIES"
    RESTO = "RESTO"
    CINE = "CINE"
    OTHER = "OTHER"

    GIFT = "CADEAUX"

    # TRANSPORT
    ROUTE = "ROUTE"
    CAR = "VOITURE"
    PARKING = "PARKING"
    BUS = "BUS"
    TRANSPORT = "TRANSPORT"
    AMENDE = "AMENDE"
    ESSENCE = "ESSENCE"

    # SANTE
    SANTE = "SANTE"
    DOC = "DOCTEUR"
    PHARM = "PHARMACIE"
    LABO = "LABO"
    BIEN = "BIENETRE"
    COIF = "COIFFEUR"

    # VACANCES
    VAC = "VACANCES"
    SAVOIE24 = "SAVOIE24"
    TOSCANE24 = "TOSCANE24"
    HYERES24 = "HYERES24"
    MAUGIO24 = "MAUGIO24"
    SERRECHE24 = "SERRECHE24"

    EPARGNE = "EPARGNE"
    INVEST = "INVEST"
    SECURE = "SECURE"

    BANK = "BANK"
    CHEQUE = "CHEQUE"
    EXPE = "EXPE"
    RETRAIT = "RETRAIT"
    DONS = "DONS"
    IMPOTS = "IMPOTS"

    TODROP = "TODROP"
