from typing import List, Tuple


from tags.tags import T

ope_todrop: List[Tuple[str, List[T]]] = [
    ("VIR Virement interne", [T.TODROP]),
    ("VIR SEPA SWISSLIFE PREVOYANCE", [T.TODROP]),
    ("Leboncoin", [T.TODROP]),
    ("VIR SEPA Bourgeais", [T.TODROP]),
    ("VIR SEPA CPCAM", [T.TODROP]),
    ("VIR SEPA GOJOB", [T.TODROP]),
    ("VIR INST ROUILLAUX", [T.TODROP]),
    ("VIR INST BOURGEAIS", [T.TODROP]),
    ("VIR SEPA Mangopay", [T.TODROP]),
    ("VIR luna", [T.TODROP]),
    ("IR INST PIACENTINI", [T.TODROP]),
    ("VIR INST MME GHYSLAINE", [T.TODROP]),
    ("VIR SEPA PIERRARD", [T.TODROP]),
    ("IR SEPA CPAM ", [T.TODROP]),
    ("VIR SEPA LEMONWAY", [T.TODROP]),
    ("VIR INST LOVELY", [T.TODROP]),
    ("VIR SEPA MME MARIE-JOSE", [T.TODROP]),
    ("VIR INST MR THIBAULT", [T.TODROP]),
    ("VIR INST NEXITY", [T.TODROP]),
    ("VIR INST JEROME", [T.TODROP]),
    ("VIR SEPA MME MORGAN", [T.TODROP]),
    ("VIR SEPA QWAMPLIFY", [T.TODROP]),
    ("VIR INST MME MARIE", [T.TODROP]),
    ("VIR SEPA FRANCE TRAVAIL", [T.TODROP]),
    ("VIR SEPA Adevinta", [T.TODROP]),
    ("VIR SEPA MME BOURGEAIS", [T.TODROP]),
    ("VIR Regularisation du compte", [T.TODROP]),
    ("VIR INST REMOT", [T.TODROP]),
    ("VIR SEPA MLLE GUILLOT", [T.TODROP]),
    ("VIR impots", [T.TODROP]),
    ("VIR Virement de Ghyslaine", [T.TODROP]),
    ("VIR SEPA M COMPAS", [T.TODROP]),
    ("VIR Cashback", [T.TODROP]),
    ("VVIR SEPA I GRAALIR", [T.TODROP]),
    ("VIR GO", [T.TODROP]),
    ("VIR INST MLE SEVERINE", [T.TODROP]),
    ("VIR INST MME SCALA", [T.TODROP]),
    ("MAXANDTHECITY", [T.TODROP]),
    ("SHOPRUNBACK", [T.TODROP]),
    ("Revolut", [T.TODROP]),
    ("binance", [T.TODROP]),
    ("VIR pizza", [T.TODROP]),
    ("BIFINITY", [T.TODROP]),
    ("Bitget", [T.TODROP]),
    ("URSSAF PACA", [T.TODROP]),
    ("BOUYGUES WEB 4", [T.TODROP]),
    ("Buchhaltung", [T.TODROP]),
    ("VIR INST WYLR", [T.TODROP]),
    ("LYFPAY", [T.TODROP]),
    ("PITRON", [T.TODROP]),
    ("IQERA", [T.TODROP]),
    ("SC MA PETITE BO", [T.TODROP]),
    ("FRAIS ADMIN A TIERS DETENTEUR", [T.TODROP]),
    ("VIR EUROPEEN EMIS LOGITEL", [T.TODROP]),
    ("VIR INSTANTANE EMIS LOGITEL", [T.TODROP]),
    ("VIR INSTANTANE EMIS NET POUR: LOVELY MUM ", [T.TODROP]),
    ("VIR EUROPEEN EMIS NET POUR: lubrano Ghyslaine ", [T.TODROP]),
    ("VIREMENT RECU PAR SOCIETE GENERALE", [T.TODROP]),
    ("Exchanged to BTC", [T.TODROP]),
    ("Scp De Benedict", [T.TODROP]),
    ("to drop", [T.TODROP]),
]
